name: CI

on:
  push:
    branches:
    - '*'
    - '!gh-pages'
  pull_request:
    branches:
    - '*'
    - '!gh-pages'

jobs:
  test:
    # The default Java on macos-12 is 11
    # https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#java
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Build sdk
      run: ./gradlew sdk:assembleRelease
    - name: Build sdk-okhttp
      run: ./gradlew sdk-okhttp:assembleRelease
    - name: Build javasample
      run: ./gradlew javasample:assembleRelease
