name: CI

on:
  push:
    branches:
      - '*'
      - '!gh-pages'
  pull_request:
    branches:
      - '*'
      - '!gh-pages'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build sdk
        run: ./gradlew sdk:assembleRelease
      - name: Build sdk-okhttp
        run: ./gradlew sdk-okhttp:assembleRelease
      - name: Build javasample
        run: ./gradlew javasample:assembleRelease