name: CI

on:
  push:
    branches:
    - '*'
    - '!gh-pages'
  pull_request:
    branches:
    - '*'
    - '!gh-pages'

jobs:
  gh-pages:
    runs-on: macos-14
    needs: ["app"]
    steps:
    - uses: actions/checkout@v4
    - run: make docs
    - name: Deploy docs to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.repository == 'authgear/authgear-sdk-android' && github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/dokka/htmlMultiModule

  test:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - run: make sdk
    - run: make sdk-okhttp
    - run: make app

  app:
    if: ${{ github.repository == 'authgear/authgear-sdk-android' }}
    runs-on: macos-14
    needs: ["test"]
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        # runs 'bundle install' and caches installed gems automatically
        bundler-cache: true
    - name: Build aab
      if: ${{ github.ref == 'refs/heads/main' }}
      env:
        STORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        STORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      run: |
        export STORE_FILE="$RUNNER_TEMP/upload_key.jks"
        echo -n "$STORE_BASE64" | base64 --decode -o "$STORE_FILE"
        make build-aab
    - name: Upload aab
      if: ${{ github.ref == 'refs/heads/main' }}
      env:
        GOOGLE_SERVICE_ACCOUNT_KEY_JSON_BASE64: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY_JSON_BASE64 }}
      run: |
        export GOOGLE_SERVICE_ACCOUNT_KEY_JSON_FILE="$RUNNER_TEMP/google_service_account_key.json"
        echo -n "$GOOGLE_SERVICE_ACCOUNT_KEY_JSON_BASE64" | base64 --decode -o "$GOOGLE_SERVICE_ACCOUNT_KEY_JSON_FILE"
        make upload-aab
