name: Publish to Maven Central

on:
  push:
    tags:
    - '*'

jobs:
  test:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/test

  publish:
    if: ${{ github.repository == 'authgear/authgear-sdk-android' && github.ref_type == 'tag' }}
    runs-on: macos-15
    needs: ["test"]
    steps:
    - uses: actions/checkout@v4
    - name: Publish to Maven Central
      env:
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.MAVEN_CENTRAL_GPG_KEY_ID }}
        ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.MAVEN_CENTRAL_GPG_KEY_PASSWORD }}
        ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.MAVEN_CENTRAL_GPG_KEY_ASCII_ARMOR_CONTENTS }}
        GITHUB_REF_NAME: ${{ github.ref_name }}
      run: ./gradlew publishToMavenCentral --no-configuration-cache
